name: Build Jekyll PR Preview

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site-pr-${{ github.event.pull_request.number }}
          path: _site/
          retention-days: 7
      
      - name: Comment PR with artifact info
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const runId = context.runId;
            const repo = context.repo;
            
            const comment = `## 🚀 Jekyll Site Built Successfully!
            
            The Jekyll site has been built and is ready for review.
            
            **Artifact Details:**
            - Artifact Name: \`jekyll-site-pr-${prNumber}\`
            - Download: [View workflow run](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId})
            
            **To test locally:**
            1. Download the artifact from the workflow run
            2. Extract the files
            3. Serve with: \`python3 -m http.server 8000\` or any local web server
            4. Visit: \`http://localhost:8000\`
            
            **Note:** Once this PR is merged to \`main\`, the site will be automatically deployed to GitHub Pages.
            `;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: repo.owner,
              repo: repo.repo,
              body: comment
            });
